server:
  port: 11600

logging:
  level:
    org.springframework: debug
    com.neusoft.mapper: debug

spring:
  application:
    name: search-server
  datasource:
    username: root
    password: 1234abc@
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.po

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
  instance:
    prefer-ip-address: true #使用ip地址向eureka server进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #设置eureka控制台中显示的注册信息
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30