server:
  port: 15000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ehusoeasom/elm-scc.git
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
  instance:
    prefer-ip-address: true #使用ip地址向eureka server进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #设置eureka控制台中显示的注册信息
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15